logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP

#spring:
#     datasource:
#        url:
#          jdbc:mysql://${DATABASE_URL:localhost}:3306/twitch?createDatabaseIfNotExist=true
#          username: ${DATABASE_USERNAME:root}
#          password: ${DATABASE_PASSWORD:secret}
#          driver-class-name: com.mysql.cj.jdbc.Driver
#
#        sql:
#          init:
#            mode: ${INIT_DB:never}
#           schema-locations: "classpath:database-init.sql"
#       jackson:
#         default-property-inclusion: non_null
#
#       cache:
#         caffeine:
#           spec: expireAfterWrite=1m
#
# logging:
#   level:
#     org.springframework.jdbc.core: DEBUG
#      org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
#      org.apache.coyote.http11.Http11InputBuffer: DEBUG
#
#twitch:
#  client-id: abc
#  secret: abc
